version: "3"
services:
 goalhub-client:
  build:
   context: ./client/
   dockerfile: Dockerfile.client
  image: goalhub-client
  stdin_open: true
  ports:
   - "5173:5173"
  depends_on:
   - goalhub-server
  networks:
   - "goalhub-app"
 goalhub-server:
  build:
   context: ./server/
   dockerfile: Dockerfile.server
  image: goalhub-server
  ports:
   - "5000:5000"
  depends_on:
   - goalhub-mongo
  networks:
   - "goalhub-app"

 goalhub-mongo:
  image: mongo:latest
  ports:
   - "27017:27017"
  networks:
   - "goalhub-app"
  volumes:
   - mongo-data:/data/db
networks:
 goalhub-app:
  driver: bridge
volumes:
 mongo-data:
  driver: local
